package com.wxm.bbsdemo.entity;

import java.util.Date;

public class Banned {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banned.bannedid
     *
     * @mbg.generated
     */
    private Long bannedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banned.banneduser_id
     *
     * @mbg.generated
     */
    private Long banneduserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banned.bannedbord_id
     *
     * @mbg.generated
     */
    private Long bannedbordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banned.time
     *
     * @mbg.generated
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banned.starttime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banned.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banned.bannedid
     *
     * @return the value of banned.bannedid
     *
     * @mbg.generated
     */
    public Long getBannedid() {
        return bannedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banned.bannedid
     *
     * @param bannedid the value for banned.bannedid
     *
     * @mbg.generated
     */
    public void setBannedid(Long bannedid) {
        this.bannedid = bannedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banned.banneduser_id
     *
     * @return the value of banned.banneduser_id
     *
     * @mbg.generated
     */
    public Long getBanneduserId() {
        return banneduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banned.banneduser_id
     *
     * @param banneduserId the value for banned.banneduser_id
     *
     * @mbg.generated
     */
    public void setBanneduserId(Long banneduserId) {
        this.banneduserId = banneduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banned.bannedbord_id
     *
     * @return the value of banned.bannedbord_id
     *
     * @mbg.generated
     */
    public Long getBannedbordId() {
        return bannedbordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banned.bannedbord_id
     *
     * @param bannedbordId the value for banned.bannedbord_id
     *
     * @mbg.generated
     */
    public void setBannedbordId(Long bannedbordId) {
        this.bannedbordId = bannedbordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banned.time
     *
     * @return the value of banned.time
     *
     * @mbg.generated
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banned.time
     *
     * @param time the value for banned.time
     *
     * @mbg.generated
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banned.starttime
     *
     * @return the value of banned.starttime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banned.starttime
     *
     * @param starttime the value for banned.starttime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banned.endtime
     *
     * @return the value of banned.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banned.endtime
     *
     * @param endtime the value for banned.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}