package com.wxm.bbsdemo.entity;

import java.util.ArrayList;
import java.util.List;

public class BannedmsgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public BannedmsgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBannedmsgIdIsNull() {
            addCriterion("bannedmsg_id is null");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdIsNotNull() {
            addCriterion("bannedmsg_id is not null");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdEqualTo(Integer value) {
            addCriterion("bannedmsg_id =", value, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdNotEqualTo(Integer value) {
            addCriterion("bannedmsg_id <>", value, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdGreaterThan(Integer value) {
            addCriterion("bannedmsg_id >", value, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bannedmsg_id >=", value, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdLessThan(Integer value) {
            addCriterion("bannedmsg_id <", value, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdLessThanOrEqualTo(Integer value) {
            addCriterion("bannedmsg_id <=", value, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdIn(List<Integer> values) {
            addCriterion("bannedmsg_id in", values, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdNotIn(List<Integer> values) {
            addCriterion("bannedmsg_id not in", values, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdBetween(Integer value1, Integer value2) {
            addCriterion("bannedmsg_id between", value1, value2, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBannedmsgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bannedmsg_id not between", value1, value2, "bannedmsgId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdIsNull() {
            addCriterion("banneduser_id is null");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdIsNotNull() {
            addCriterion("banneduser_id is not null");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdEqualTo(Long value) {
            addCriterion("banneduser_id =", value, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdNotEqualTo(Long value) {
            addCriterion("banneduser_id <>", value, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdGreaterThan(Long value) {
            addCriterion("banneduser_id >", value, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("banneduser_id >=", value, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdLessThan(Long value) {
            addCriterion("banneduser_id <", value, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdLessThanOrEqualTo(Long value) {
            addCriterion("banneduser_id <=", value, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdIn(List<Long> values) {
            addCriterion("banneduser_id in", values, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdNotIn(List<Long> values) {
            addCriterion("banneduser_id not in", values, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdBetween(Long value1, Long value2) {
            addCriterion("banneduser_id between", value1, value2, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBanneduserIdNotBetween(Long value1, Long value2) {
            addCriterion("banneduser_id not between", value1, value2, "banneduserId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdIsNull() {
            addCriterion("bannedby_id is null");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdIsNotNull() {
            addCriterion("bannedby_id is not null");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdEqualTo(Long value) {
            addCriterion("bannedby_id =", value, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdNotEqualTo(Long value) {
            addCriterion("bannedby_id <>", value, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdGreaterThan(Long value) {
            addCriterion("bannedby_id >", value, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("bannedby_id >=", value, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdLessThan(Long value) {
            addCriterion("bannedby_id <", value, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdLessThanOrEqualTo(Long value) {
            addCriterion("bannedby_id <=", value, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdIn(List<Long> values) {
            addCriterion("bannedby_id in", values, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdNotIn(List<Long> values) {
            addCriterion("bannedby_id not in", values, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdBetween(Long value1, Long value2) {
            addCriterion("bannedby_id between", value1, value2, "bannedbyId");
            return (Criteria) this;
        }

        public Criteria andBannedbyIdNotBetween(Long value1, Long value2) {
            addCriterion("bannedby_id not between", value1, value2, "bannedbyId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bannedmsg
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}