package com.wxm.bbsdemo.entity;

public class Board {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.boardid
     *
     * @mbg.generated
     */
    private Long boardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.boardname
     *
     * @mbg.generated
     */
    private String boardname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.post_num
     *
     * @mbg.generated
     */
    private Long postNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.postreply_num
     *
     * @mbg.generated
     */
    private Long postreplyNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.notice
     *
     * @mbg.generated
     */
    private String notice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.boardid
     *
     * @return the value of board.boardid
     *
     * @mbg.generated
     */
    public Long getBoardid() {
        return boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.boardid
     *
     * @param boardid the value for board.boardid
     *
     * @mbg.generated
     */
    public void setBoardid(Long boardid) {
        this.boardid = boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.boardname
     *
     * @return the value of board.boardname
     *
     * @mbg.generated
     */
    public String getBoardname() {
        return boardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.boardname
     *
     * @param boardname the value for board.boardname
     *
     * @mbg.generated
     */
    public void setBoardname(String boardname) {
        this.boardname = boardname == null ? null : boardname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.info
     *
     * @return the value of board.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.info
     *
     * @param info the value for board.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.post_num
     *
     * @return the value of board.post_num
     *
     * @mbg.generated
     */
    public Long getPostNum() {
        return postNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.post_num
     *
     * @param postNum the value for board.post_num
     *
     * @mbg.generated
     */
    public void setPostNum(Long postNum) {
        this.postNum = postNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.postreply_num
     *
     * @return the value of board.postreply_num
     *
     * @mbg.generated
     */
    public Long getPostreplyNum() {
        return postreplyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.postreply_num
     *
     * @param postreplyNum the value for board.postreply_num
     *
     * @mbg.generated
     */
    public void setPostreplyNum(Long postreplyNum) {
        this.postreplyNum = postreplyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.notice
     *
     * @return the value of board.notice
     *
     * @mbg.generated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.notice
     *
     * @param notice the value for board.notice
     *
     * @mbg.generated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    @Override
    public String toString() {
        return "Board{" +
                "boardid=" + boardid +
                ", boardname='" + boardname + '\'' +
                ", info='" + info + '\'' +
                ", postNum=" + postNum +
                ", postreplyNum=" + postreplyNum +
                ", notice='" + notice + '\'' +
                '}';
    }
}