package com.wxm.bbsdemo.entity;


import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageid
     *
     * @mbg.generated
     */
    private Integer messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.senderid
     *
     * @mbg.generated
     */
    private Long senderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receiverid
     *
     * @mbg.generated
     */
    private Long receiverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sendDateReform
     *
     * @mbg.generated
     */
    private DateReform sendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_received
     *
     * @mbg.generated
     */
    private Boolean isReceived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_notice
     *
     * @mbg.generated
     */
    private Boolean isNotice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageid
     *
     * @return the value of message.messageid
     *
     * @mbg.generated
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageid
     *
     * @param messageid the value for message.messageid
     *
     * @mbg.generated
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.senderid
     *
     * @return the value of message.senderid
     *
     * @mbg.generated
     */
    public Long getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.senderid
     *
     * @param senderid the value for message.senderid
     *
     * @mbg.generated
     */
    public void setSenderid(Long senderid) {
        this.senderid = senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receiverid
     *
     * @return the value of message.receiverid
     *
     * @mbg.generated
     */
    public Long getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receiverid
     *
     * @param receiverid the value for message.receiverid
     *
     * @mbg.generated
     */
    public void setReceiverid(Long receiverid) {
        this.receiverid = receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sendDateReform
     *
     * @return the value of message.sendDateReform
     *
     * @mbg.generated
     */
    public Date getSenddate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sendDateReform
     *
     * @param sendDate the value for message.sendDateReform
     *
     * @mbg.generated
     */
    public void setSenddate(Date sendDate) {
        this.sendDate = new DateReform(sendDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_received
     *
     * @return the value of message.is_received
     *
     * @mbg.generated
     */
    public Boolean getIsReceived() {
        return isReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_received
     *
     * @param isReceived the value for message.is_received
     *
     * @mbg.generated
     */
    public void setIsReceived(Boolean isReceived) {
        this.isReceived = isReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_notice
     *
     * @return the value of message.is_notice
     *
     * @mbg.generated
     */
    public Boolean getIsNotice() {
        return isNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_notice
     *
     * @param isNotice the value for message.is_notice
     *
     * @mbg.generated
     */
    public void setIsNotice(Boolean isNotice) {
        this.isNotice = isNotice;
    }

    @Override
    public String toString() {
        return "Message{" +
                "messageid=" + messageid +
                ", senderid=" + senderid +
                ", receiverid=" + receiverid +
                ", message='" + message + '\'' +
                ", sendDateReform=" + sendDate +
                ", isReceived=" + isReceived +
                ", isNotice=" + isNotice +
                '}';
    }
}