package com.wxm.bbsdemo.entity;


import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.postid
     *
     * @mbg.generated
     */
    private Long postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.boardid
     *
     * @mbg.generated
     */
    private Long boardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.themeid
     *
     * @mbg.generated
     */
    private Long themeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.postby_id
     *
     * @mbg.generated
     */
    private Long postbyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Postdate
     *
     * @mbg.generated
     */
    private DateReform postdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.viewcount
     *
     * @mbg.generated
     */
    private Long viewcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.postreply_num
     *
     * @mbg.generated
     */
    private Long postreplyNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.postid
     *
     * @return the value of post.postid
     *
     * @mbg.generated
     */
    public Long getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.postid
     *
     * @param postid the value for post.postid
     *
     * @mbg.generated
     */
    public void setPostid(Long postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.boardid
     *
     * @return the value of post.boardid
     *
     * @mbg.generated
     */
    public Long getBoardid() {
        return boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.boardid
     *
     * @param boardid the value for post.boardid
     *
     * @mbg.generated
     */
    public void setBoardid(Long boardid) {
        this.boardid = boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.name
     *
     * @return the value of post.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.name
     *
     * @param name the value for post.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.themeid
     *
     * @return the value of post.themeid
     *
     * @mbg.generated
     */
    public Long getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.themeid
     *
     * @param themeid the value for post.themeid
     *
     * @mbg.generated
     */
    public void setThemeid(Long themeid) {
        this.themeid = themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.postby_id
     *
     * @return the value of post.postby_id
     *
     * @mbg.generated
     */
    public Long getPostbyId() {
        return postbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.postby_id
     *
     * @param postbyId the value for post.postby_id
     *
     * @mbg.generated
     */
    public void setPostbyId(Long postbyId) {
        this.postbyId = postbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Postdate
     *
     * @return the value of post.Postdate
     *
     * @mbg.generated
     */
    public Date getPostdate() {
        return postdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Postdate
     *
     * @param postdate the value for post.Postdate
     *
     * @mbg.generated
     */
    public void setPostdate(Date postdate) {
        this.postdate = new DateReform(postdate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.viewcount
     *
     * @return the value of post.viewcount
     *
     * @mbg.generated
     */
    public Long getViewcount() {
        return viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.viewcount
     *
     * @param viewcount the value for post.viewcount
     *
     * @mbg.generated
     */
    public void setViewcount(Long viewcount) {
        this.viewcount = viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.postreply_num
     *
     * @return the value of post.postreply_num
     *
     * @mbg.generated
     */
    public Long getPostreplyNum() {
        return postreplyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.postreply_num
     *
     * @param postreplyNum the value for post.postreply_num
     *
     * @mbg.generated
     */
    public void setPostreplyNum(Long postreplyNum) {
        this.postreplyNum = postreplyNum;
    }

    @Override
    public String toString() {
        return "Post{" +
                "postid=" + postid +
                ", boardid=" + boardid +
                ", name='" + name + '\'' +
                ", themeid=" + themeid +
                ", postbyId=" + postbyId +
                ", Postdate=" + postdate +
                ", viewcount=" + viewcount +
                ", postreplyNum=" + postreplyNum +
                '}';
    }
}