package com.wxm.bbsdemo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PostreplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postreply
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postreply
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postreply
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public PostreplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table postreply
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPostreplyIdIsNull() {
            addCriterion("postreply_id is null");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdIsNotNull() {
            addCriterion("postreply_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdEqualTo(Long value) {
            addCriterion("postreply_id =", value, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdNotEqualTo(Long value) {
            addCriterion("postreply_id <>", value, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdGreaterThan(Long value) {
            addCriterion("postreply_id >", value, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("postreply_id >=", value, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdLessThan(Long value) {
            addCriterion("postreply_id <", value, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdLessThanOrEqualTo(Long value) {
            addCriterion("postreply_id <=", value, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdIn(List<Long> values) {
            addCriterion("postreply_id in", values, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdNotIn(List<Long> values) {
            addCriterion("postreply_id not in", values, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdBetween(Long value1, Long value2) {
            addCriterion("postreply_id between", value1, value2, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostreplyIdNotBetween(Long value1, Long value2) {
            addCriterion("postreply_id not between", value1, value2, "postreplyId");
            return (Criteria) this;
        }

        public Criteria andPostidIsNull() {
            addCriterion("postid is null");
            return (Criteria) this;
        }

        public Criteria andPostidIsNotNull() {
            addCriterion("postid is not null");
            return (Criteria) this;
        }

        public Criteria andPostidEqualTo(Long value) {
            addCriterion("postid =", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidNotEqualTo(Long value) {
            addCriterion("postid <>", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidGreaterThan(Long value) {
            addCriterion("postid >", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidGreaterThanOrEqualTo(Long value) {
            addCriterion("postid >=", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidLessThan(Long value) {
            addCriterion("postid <", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidLessThanOrEqualTo(Long value) {
            addCriterion("postid <=", value, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidIn(List<Long> values) {
            addCriterion("postid in", values, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidNotIn(List<Long> values) {
            addCriterion("postid not in", values, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidBetween(Long value1, Long value2) {
            addCriterion("postid between", value1, value2, "postid");
            return (Criteria) this;
        }

        public Criteria andPostidNotBetween(Long value1, Long value2) {
            addCriterion("postid not between", value1, value2, "postid");
            return (Criteria) this;
        }

        public Criteria andReplybyIdIsNull() {
            addCriterion("replyby_id is null");
            return (Criteria) this;
        }

        public Criteria andReplybyIdIsNotNull() {
            addCriterion("replyby_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplybyIdEqualTo(Long value) {
            addCriterion("replyby_id =", value, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdNotEqualTo(Long value) {
            addCriterion("replyby_id <>", value, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdGreaterThan(Long value) {
            addCriterion("replyby_id >", value, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("replyby_id >=", value, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdLessThan(Long value) {
            addCriterion("replyby_id <", value, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdLessThanOrEqualTo(Long value) {
            addCriterion("replyby_id <=", value, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdIn(List<Long> values) {
            addCriterion("replyby_id in", values, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdNotIn(List<Long> values) {
            addCriterion("replyby_id not in", values, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdBetween(Long value1, Long value2) {
            addCriterion("replyby_id between", value1, value2, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplybyIdNotBetween(Long value1, Long value2) {
            addCriterion("replyby_id not between", value1, value2, "replybyId");
            return (Criteria) this;
        }

        public Criteria andReplydateIsNull() {
            addCriterion("replydate is null");
            return (Criteria) this;
        }

        public Criteria andReplydateIsNotNull() {
            addCriterion("replydate is not null");
            return (Criteria) this;
        }

        public Criteria andReplydateEqualTo(Date value) {
            addCriterion("replydate =", value, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateNotEqualTo(Date value) {
            addCriterion("replydate <>", value, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateGreaterThan(Date value) {
            addCriterion("replydate >", value, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateGreaterThanOrEqualTo(Date value) {
            addCriterion("replydate >=", value, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateLessThan(Date value) {
            addCriterion("replydate <", value, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateLessThanOrEqualTo(Date value) {
            addCriterion("replydate <=", value, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateIn(List<Date> values) {
            addCriterion("replydate in", values, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateNotIn(List<Date> values) {
            addCriterion("replydate not in", values, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateBetween(Date value1, Date value2) {
            addCriterion("replydate between", value1, value2, "replydate");
            return (Criteria) this;
        }

        public Criteria andReplydateNotBetween(Date value1, Date value2) {
            addCriterion("replydate not between", value1, value2, "replydate");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andFloornumIsNull() {
            addCriterion("floornum is null");
            return (Criteria) this;
        }

        public Criteria andFloornumIsNotNull() {
            addCriterion("floornum is not null");
            return (Criteria) this;
        }

        public Criteria andFloornumEqualTo(Integer value) {
            addCriterion("floornum =", value, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumNotEqualTo(Integer value) {
            addCriterion("floornum <>", value, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumGreaterThan(Integer value) {
            addCriterion("floornum >", value, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumGreaterThanOrEqualTo(Integer value) {
            addCriterion("floornum >=", value, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumLessThan(Integer value) {
            addCriterion("floornum <", value, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumLessThanOrEqualTo(Integer value) {
            addCriterion("floornum <=", value, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumIn(List<Integer> values) {
            addCriterion("floornum in", values, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumNotIn(List<Integer> values) {
            addCriterion("floornum not in", values, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumBetween(Integer value1, Integer value2) {
            addCriterion("floornum between", value1, value2, "floornum");
            return (Criteria) this;
        }

        public Criteria andFloornumNotBetween(Integer value1, Integer value2) {
            addCriterion("floornum not between", value1, value2, "floornum");
            return (Criteria) this;
        }

        public Criteria andModifybyIdIsNull() {
            addCriterion("modifyby_id is null");
            return (Criteria) this;
        }

        public Criteria andModifybyIdIsNotNull() {
            addCriterion("modifyby_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifybyIdEqualTo(Long value) {
            addCriterion("modifyby_id =", value, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdNotEqualTo(Long value) {
            addCriterion("modifyby_id <>", value, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdGreaterThan(Long value) {
            addCriterion("modifyby_id >", value, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modifyby_id >=", value, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdLessThan(Long value) {
            addCriterion("modifyby_id <", value, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdLessThanOrEqualTo(Long value) {
            addCriterion("modifyby_id <=", value, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdIn(List<Long> values) {
            addCriterion("modifyby_id in", values, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdNotIn(List<Long> values) {
            addCriterion("modifyby_id not in", values, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdBetween(Long value1, Long value2) {
            addCriterion("modifyby_id between", value1, value2, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifybyIdNotBetween(Long value1, Long value2) {
            addCriterion("modifyby_id not between", value1, value2, "modifybyId");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("modifydate is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("modifydate is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("modifydate =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("modifydate <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("modifydate >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifydate >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("modifydate <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("modifydate <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("modifydate in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("modifydate not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("modifydate between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("modifydate not between", value1, value2, "modifydate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table postreply
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table postreply
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}