package com.wxm.bbsdemo.entity;

import java.util.Date;

public class Postreply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.postreply_id
     *
     * @mbg.generated
     */
    private Long postreplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.postid
     *
     * @mbg.generated
     */
    private Long postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.replyby_id
     *
     * @mbg.generated
     */
    private Long replybyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.replydate
     *
     * @mbg.generated
     */
    private DateReform replydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.floornum
     *
     * @mbg.generated
     */
    private Integer floornum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.modifyby_id
     *
     * @mbg.generated
     */
    private Long modifybyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply.modifydate
     *
     * @mbg.generated
     */
    private DateReform modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.postreply_id
     *
     * @return the value of postreply.postreply_id
     *
     * @mbg.generated
     */
    public Long getPostreplyId() {
        return postreplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.postreply_id
     *
     * @param postreplyId the value for postreply.postreply_id
     *
     * @mbg.generated
     */
    public void setPostreplyId(Long postreplyId) {
        this.postreplyId = postreplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.postid
     *
     * @return the value of postreply.postid
     *
     * @mbg.generated
     */
    public Long getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.postid
     *
     * @param postid the value for postreply.postid
     *
     * @mbg.generated
     */
    public void setPostid(Long postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.replyby_id
     *
     * @return the value of postreply.replyby_id
     *
     * @mbg.generated
     */
    public Long getReplybyId() {
        return replybyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.replyby_id
     *
     * @param replybyId the value for postreply.replyby_id
     *
     * @mbg.generated
     */
    public void setReplybyId(Long replybyId) {
        this.replybyId = replybyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.replydate
     *
     * @return the value of postreply.replydate
     *
     * @mbg.generated
     */
    public Date getReplydate() {
        return replydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.replydate
     *
     * @param replydate the value for postreply.replydate
     *
     * @mbg.generated
     */
    public void setReplydate(Date replydate) {
        this.replydate = new DateReform(replydate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.content
     *
     * @return the value of postreply.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.content
     *
     * @param content the value for postreply.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.floornum
     *
     * @return the value of postreply.floornum
     *
     * @mbg.generated
     */
    public Integer getFloornum() {
        return floornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.floornum
     *
     * @param floornum the value for postreply.floornum
     *
     * @mbg.generated
     */
    public void setFloornum(Integer floornum) {
        this.floornum = floornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.modifyby_id
     *
     * @return the value of postreply.modifyby_id
     *
     * @mbg.generated
     */
    public Long getModifybyId() {
        return modifybyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.modifyby_id
     *
     * @param modifybyId the value for postreply.modifyby_id
     *
     * @mbg.generated
     */
    public void setModifybyId(Long modifybyId) {
        this.modifybyId = modifybyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply.modifydate
     *
     * @return the value of postreply.modifydate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply.modifydate
     *
     * @param modifydate the value for postreply.modifydate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {

        this.modifydate = new DateReform(modifydate);
    }

    @Override
    public String toString() {
        return "Postreply{" +
                "postreplyId=" + postreplyId +
                ", postid=" + postid +
                ", replybyId=" + replybyId +
                ", replydate=" + replydate +
                ", content='" + content + '\'' +
                ", floornum=" + floornum +
                ", modifybyId=" + modifybyId +
                ", modifydate=" + modifydate +
                '}';
    }
}