package com.wxm.bbsdemo.entity;

import java.util.ArrayList;
import java.util.List;

public class PostthemeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public PostthemeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPostthemeIdIsNull() {
            addCriterion("posttheme_id is null");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdIsNotNull() {
            addCriterion("posttheme_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdEqualTo(Long value) {
            addCriterion("posttheme_id =", value, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdNotEqualTo(Long value) {
            addCriterion("posttheme_id <>", value, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdGreaterThan(Long value) {
            addCriterion("posttheme_id >", value, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("posttheme_id >=", value, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdLessThan(Long value) {
            addCriterion("posttheme_id <", value, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdLessThanOrEqualTo(Long value) {
            addCriterion("posttheme_id <=", value, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdIn(List<Long> values) {
            addCriterion("posttheme_id in", values, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdNotIn(List<Long> values) {
            addCriterion("posttheme_id not in", values, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdBetween(Long value1, Long value2) {
            addCriterion("posttheme_id between", value1, value2, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andPostthemeIdNotBetween(Long value1, Long value2) {
            addCriterion("posttheme_id not between", value1, value2, "postthemeId");
            return (Criteria) this;
        }

        public Criteria andThemenameIsNull() {
            addCriterion("themename is null");
            return (Criteria) this;
        }

        public Criteria andThemenameIsNotNull() {
            addCriterion("themename is not null");
            return (Criteria) this;
        }

        public Criteria andThemenameEqualTo(String value) {
            addCriterion("themename =", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameNotEqualTo(String value) {
            addCriterion("themename <>", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameGreaterThan(String value) {
            addCriterion("themename >", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameGreaterThanOrEqualTo(String value) {
            addCriterion("themename >=", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameLessThan(String value) {
            addCriterion("themename <", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameLessThanOrEqualTo(String value) {
            addCriterion("themename <=", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameLike(String value) {
            addCriterion("themename like", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameNotLike(String value) {
            addCriterion("themename not like", value, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameIn(List<String> values) {
            addCriterion("themename in", values, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameNotIn(List<String> values) {
            addCriterion("themename not in", values, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameBetween(String value1, String value2) {
            addCriterion("themename between", value1, value2, "themename");
            return (Criteria) this;
        }

        public Criteria andThemenameNotBetween(String value1, String value2) {
            addCriterion("themename not between", value1, value2, "themename");
            return (Criteria) this;
        }

        public Criteria andBoardidIsNull() {
            addCriterion("boardid is null");
            return (Criteria) this;
        }

        public Criteria andBoardidIsNotNull() {
            addCriterion("boardid is not null");
            return (Criteria) this;
        }

        public Criteria andBoardidEqualTo(Long value) {
            addCriterion("boardid =", value, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidNotEqualTo(Long value) {
            addCriterion("boardid <>", value, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidGreaterThan(Long value) {
            addCriterion("boardid >", value, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidGreaterThanOrEqualTo(Long value) {
            addCriterion("boardid >=", value, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidLessThan(Long value) {
            addCriterion("boardid <", value, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidLessThanOrEqualTo(Long value) {
            addCriterion("boardid <=", value, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidIn(List<Long> values) {
            addCriterion("boardid in", values, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidNotIn(List<Long> values) {
            addCriterion("boardid not in", values, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidBetween(Long value1, Long value2) {
            addCriterion("boardid between", value1, value2, "boardid");
            return (Criteria) this;
        }

        public Criteria andBoardidNotBetween(Long value1, Long value2) {
            addCriterion("boardid not between", value1, value2, "boardid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posttheme
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}