package com.wxm.bbsdemo.entity;

public class Posttheme {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posttheme.posttheme_id
     *
     * @mbg.generated
     */
    private Long postthemeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posttheme.themename
     *
     * @mbg.generated
     */
    private String themename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posttheme.boardid
     *
     * @mbg.generated
     */
    private Long boardid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posttheme.posttheme_id
     *
     * @return the value of posttheme.posttheme_id
     *
     * @mbg.generated
     */
    public Long getPostthemeId() {
        return postthemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posttheme.posttheme_id
     *
     * @param postthemeId the value for posttheme.posttheme_id
     *
     * @mbg.generated
     */
    public void setPostthemeId(Long postthemeId) {
        this.postthemeId = postthemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posttheme.themename
     *
     * @return the value of posttheme.themename
     *
     * @mbg.generated
     */
    public String getThemename() {
        return themename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posttheme.themename
     *
     * @param themename the value for posttheme.themename
     *
     * @mbg.generated
     */
    public void setThemename(String themename) {
        this.themename = themename == null ? null : themename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posttheme.boardid
     *
     * @return the value of posttheme.boardid
     *
     * @mbg.generated
     */
    public Long getBoardid() {
        return boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posttheme.boardid
     *
     * @param boardid the value for posttheme.boardid
     *
     * @mbg.generated
     */
    public void setBoardid(Long boardid) {
        this.boardid = boardid;
    }

    @Override
    public String toString() {
        return "Posttheme{" +
                "postthemeId=" + postthemeId +
                ", themename='" + themename + '\'' +
                ", boardid=" + boardid +
                '}';
    }
}