package com.wxm.bbsdemo.entity;

import java.util.Date;

public class PostreplyComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply_comment.postreply_comment_id
     *
     * @mbg.generated
     */
    private Long postreplyCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply_comment.postreply_id
     *
     * @mbg.generated
     */
    private Long postreplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply_comment.commentby_id
     *
     * @mbg.generated
     */
    private Long commentbyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply_comment.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postreply_comment.commentdate
     *
     * @mbg.generated
     */
    private Date commentdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply_comment.postreply_comment_id
     *
     * @return the value of postreply_comment.postreply_comment_id
     *
     * @mbg.generated
     */
    public Long getPostreplyCommentId() {
        return postreplyCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply_comment.postreply_comment_id
     *
     * @param postreplyCommentId the value for postreply_comment.postreply_comment_id
     *
     * @mbg.generated
     */
    public void setPostreplyCommentId(Long postreplyCommentId) {
        this.postreplyCommentId = postreplyCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply_comment.postreply_id
     *
     * @return the value of postreply_comment.postreply_id
     *
     * @mbg.generated
     */
    public Long getPostreplyId() {
        return postreplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply_comment.postreply_id
     *
     * @param postreplyId the value for postreply_comment.postreply_id
     *
     * @mbg.generated
     */
    public void setPostreplyId(Long postreplyId) {
        this.postreplyId = postreplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply_comment.commentby_id
     *
     * @return the value of postreply_comment.commentby_id
     *
     * @mbg.generated
     */
    public Long getCommentbyId() {
        return commentbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply_comment.commentby_id
     *
     * @param commentbyId the value for postreply_comment.commentby_id
     *
     * @mbg.generated
     */
    public void setCommentbyId(Long commentbyId) {
        this.commentbyId = commentbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply_comment.comment
     *
     * @return the value of postreply_comment.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply_comment.comment
     *
     * @param comment the value for postreply_comment.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postreply_comment.commentdate
     *
     * @return the value of postreply_comment.commentdate
     *
     * @mbg.generated
     */
    public Date getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postreply_comment.commentdate
     *
     * @param commentdate the value for postreply_comment.commentdate
     *
     * @mbg.generated
     */
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }

    @Override
    public String toString() {
        return "PostreplyComment{" +
                "postreplyCommentId=" + postreplyCommentId +
                ", postreplyId=" + postreplyId +
                ", commentbyId=" + commentbyId +
                ", comment='" + comment + '\'' +
                ", commentdate=" + commentdate +
                '}';
    }
}