server:
  port:
spring:
  datasource:
    name: bbs
    url: jdbc:mysql://127.0.0.1:3306/bbs?useSSL=false
    username: root
    password: 13072213550
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mail:
    host: smtp.wxmpoi.xyz
  # mvc:
    #throw-exception-if-no-handler-found: true
    #static-path-pattern: /statics/**
    username: coursework-2019@wxmpoi.xyz
    port: 25
    protocol: smtp
    password: wxm1997WXM
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wxm.bbsdemo.entity
##mapper:
##  mappers:
##    - tk.mybatis.mapper.common.Mapper
##  not-empty: false
##  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql