package com.wxm.bbsdemo.mapper;

import com.wxm.bbsdemo.entity.Bannedmsg;
import com.wxm.bbsdemo.entity.BannedmsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BannedmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    long countByExample(BannedmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int deleteByExample(BannedmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bannedmsgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int insert(Bannedmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int insertSelective(Bannedmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    List<Bannedmsg> selectByExample(BannedmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    Bannedmsg selectByPrimaryKey(Integer bannedmsgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bannedmsg record, @Param("example") BannedmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bannedmsg record, @Param("example") BannedmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bannedmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannedmsg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bannedmsg record);
}