package com.wxm.bbsdemo.mapper;

import com.wxm.bbsdemo.entity.Banned;
import com.wxm.bbsdemo.entity.BannedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BannedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    long countByExample(BannedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int deleteByExample(BannedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long bannedid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int insert(Banned record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int insertSelective(Banned record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    List<Banned> selectByExample(BannedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    Banned selectByPrimaryKey(Long bannedid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Banned record, @Param("example") BannedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Banned record, @Param("example") BannedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Banned record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banned
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Banned record);
}