package com.wxm.bbsdemo.mapper;

import com.wxm.bbsdemo.entity.Posttheme;
import com.wxm.bbsdemo.entity.PostthemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostthemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    long countByExample(PostthemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int deleteByExample(PostthemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long postthemeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int insert(Posttheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int insertSelective(Posttheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    List<Posttheme> selectByExample(PostthemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    Posttheme selectByPrimaryKey(Long postthemeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Posttheme record, @Param("example") PostthemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Posttheme record, @Param("example") PostthemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Posttheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posttheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Posttheme record);
}