package com.wxm.bbsdemo.mapper;

import com.wxm.bbsdemo.entity.Postreply;
import com.wxm.bbsdemo.entity.PostreplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostreplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    long countByExample(PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int deleteByExample(PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long postreplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int insert(Postreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int insertSelective(Postreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    List<Postreply> selectByExample(PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    Postreply selectByPrimaryKey(Long postreplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Postreply record, @Param("example") PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Postreply record, @Param("example") PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Postreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Postreply record);
}