package com.wxm.bbsdemo.mapper;

import com.wxm.bbsdemo.entity.PostreplyComment;
import com.wxm.bbsdemo.entity.PostreplyCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostreplyCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    long countByExample(PostreplyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int deleteByExample(PostreplyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long postreplyCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int insert(PostreplyComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int insertSelective(PostreplyComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    List<PostreplyComment> selectByExample(PostreplyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    PostreplyComment selectByPrimaryKey(Long postreplyCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PostreplyComment record, @Param("example") PostreplyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PostreplyComment record, @Param("example") PostreplyCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PostreplyComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postreply_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostreplyComment record);
}